Сортировка
htmlacademy-ecmascript/443953-cinemaddict-12 pull request #7
Opened 2020-08-31 22:11 UTC by andrex002

2020-09-01 06:12 UTC, Shv-sergey70 requested changes

2020-09-01 06:12 UTC, Shv-sergey70 commented on src/utils/films.js
> +   return filmB.dateOfProduction - filmA.dateOfProduction;
`dateOfProduction` такого поля же нет в структуре?

2020-09-01 06:12 UTC, Shv-sergey70 commented on src/utils/films.js
> +};
Используй короткий синтаксис стрелочных функций

2020-09-01 06:12 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +    render(this._movieListContainer, this._contentSectionComponent, RenderPosition.BEFOREEND);
Эти два действия делать не нужно. Проблема в том, что если ты здесь делаешь перерисовку, то переменные `this._filmsListContainer` и `this._filmsListElement` по-прежнему будут ссылкаться на старый контейнер. Хотя ты его здесь перерисовываешь.

Это происходит потому что ты в конструкторе 1 раз делаешь поиск querySelector на 27-28 строчках. После этого конструктор уже не срабатывает и данные в переменных не обновляются.

Поэтому самое просто решение это сделать так:
```
this._filmsListContainer.innerHTML = ``;
```

2020-09-02 14:17 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
>      this._renderMainContent();
Если я несколько раз кликаю по сортировке, то получаю много экстра списков. Надо это поправить
![Снимок экрана 2020-09-02 в 21 08 59](https://user-images.githubusercontent.com/35741647/91994218-8f987c80-ed60-11ea-9c31-689d86a6cf8b.png)

2020-09-02 14:17 UTC, Shv-sergey70 commented on src/view/sort.js
> +    const sortButtons = document.querySelectorAll(`.sort__button`);
Компонент - это то, что является независимым по отношению ко всему остальному коду. Компонент принимает информацию через параметры конструктора/методы.

Если ты делаешь поиск дом-элементов через `document.querySelectorAll` - ты разрушаешь концепцию независимости компонентов, так как теперь он зависим от внешнего кода (document). 

Компоненты вообще не должны никогда ничего искать через document. Все с чем может работать компонент - это его разметка.

Поэтому в данном случае, `document` заменяем на `this.getElement()`.
```
this.getElement().querySelectorAll(`.sort__button`)
```

2020-09-02 14:17 UTC, Shv-sergey70 commented on src/view/sort.js
> +    }
Нет надобности использовать цикл `for of`, когда можно использовать встроенные циклы. Например, любая коллекция дом-элементов имеет метод `forEach`, поэтому можно так:
```
    this.getElement().querySelectorAll(`.sort__button`)
      .forEach((button) => {
        if (button.classList.contains(`sort__button--active`)) {
          button.classList.remove(`sort__button--active`);
        }
      });
```

2020-09-03 05:11 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +    remove(this._filmsListExtraMostCommentedComponent);
Окей, это как вариант решения. Но зачем тебе вообще перерисовывать экстра карточки при сортировке? Они ведь от этого не меняются. Тебе бы просто не перерисовывать их в целом

2020-09-03 05:11 UTC, merged

2020-09-03 19:16 UTC, andrex002 commented on src/presenter/movie-list.js
> +    remove(this._filmsListExtraMostCommentedComponent);
Рендеринг блоков extra у меня включен в рендеринг главного контента, который я вызываю при перерисовке. Поэтому приходится удалять extra-блоки. Может просто отделить перерисовку extra от карточек фильмов?